# Стратегия 1: YouTube TCP
--filter-tcp=80,443
--hostlist=./hostlists/youtube.txt
--dpi-desync=multisplit
--dpi-desync-split-seqovl=1
--dpi-desync-split-pos=midsld-1
--comment="YouTube TCP"

--new
# Стратегия 2: YouTube QUIC (UDP)
--filter-udp=443
--hostlist=./hostlists/youtube.txt
--dpi-desync=fake
--dpi-desync-repeats=11
--comment="YouTube QUIC"
